### ISSUE TITLE
Land Rover and Car Lock

### ISSUE THREAD

**Issue by s0ulska** [42MonthsAfter/Public#6] opened 2022-05-25 20:04 UTC
Land Rover will not take car lock.

**Comment by BnYrB** [comment] 2022-05-25 22:21
I was just able to put one on. I was standing between the front and back door and looking almost down at my feet.

**Comment by s0ulska** [comment] 2022-05-26 02:12
cant get it... yellow is the color

**Comment by BnYrB** [comment] 2022-05-27 18:04
I was just able to do it. Let me know the next time you are on and I'll meet up and we will try. If you are trying in the holler you might not be able to, just FYI

**Comment by BnYrB** [comment] 2022-05-30 01:33
Closing as I can't reproduce this one and I'm closing this repo.

**Closed by BnYrB** 2022-05-30 01:33 UTC
Labels: bug
